name: Tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main, testing-singlestore-images]
jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # deno-version: [1.19.x]
      max-parallel: 3

    services:
      singlestoredb:
        image: ghcr.io/singlestore-labs/singlestoredb-dev
        ports:
          - 3306:3306
          - 8080:8080
          - 9000:9000
        env:
          ROOT_PASSWORD: test
          SINGLESTORE_LICENSE: ${{ secrets.SINGLESTORE_LICENSE }}
        # volumes:
        #   - ${GITHUB_WORKSPACE}/tests/init.sql:/init.sql

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init SingleStore database
        run: |
          mysql -u root -ptest -h 127.0.0.1 < /${GITHUB_WORKSPACE}/tests/init.sql

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Install Deno ${{ matrix.deno-version }}
      #   uses: denolib/setup-deno@v2
      #   with:
      #     deno-version: ${{ matrix.deno-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Run node tests
        run: pnpm test

      # - name: Run browser tests
      #   run: pnpm run test:browser

      # - name: Run deno tests
      #   run: pnpm run test:deno

      - name: Run esm check
        run: cd examples/esm && npm i && npm start

      - name: Run cjs check
        run: cd examples/cjs && npm i && npm start
